name: Archive Gemini Conversations

on:
  push:
  workflow_dispatch:

# Always run at most one instance of the workflow at a time.
# When combined with the `ref` option on `actions/checkout@v5` in the `action.yml` file,
# this prevents a race condition in which a previous automatic update isn't counted when adding or removing content.

# For example:
# - Commit 1 (adds ID 'abc')
# - Commit 2 (removes ID 'abc', which triggers this action)
# - Automatic commit 3 (triggered by Commit 1, which adds HTML for 'abc')
# - Automatic commit 4 (triggered by Commit 2, which removes nothing; it should have removed the HTML for 'abc')

# This fixes the race condition in two ways:
# - If a user pushes a new commit (commit 2) before the action triggered by the first one has started,
#   the action will check out the latest commit (commit 2), not the one that triggered it (commit 1).
# - If a user pushes a new commit (commit 2) after the first action has started,
#   the second action will wait for the first action's automatic commit (commit 3) to be pushed.
#   The second action will then check out the latest commit (commit 3) when it runs.
concurrency:
  group: ${{ github.ref_name }}

jobs:
  archive-gemini-conversations:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: mon-jai/gemini-archiver@main
