name: Archive Gemini Conversations

on:
  push:
  workflow_dispatch:

jobs:
  archive-gemini-conversations:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: mon-jai/gemini-archiver@main
